### ISSUE TITLE
Characters and Lines Abbreviations

### ISSUE THREAD

**Issue by fletcher** [fletcher/MultiMarkdown-Composer-Localization#4]
When the editor view is too small, the Info bar shortens to abbreviations ("Words" -> "W").  This is particularly true on the iPhone zum Beispiel.

What should "Characters" and "Lines" ("Zeichen" and "Zeilen") be, since they both start with "Z"?

Danke!

**Comment by andreasvollmer** [comment]
"Zeichen" is very common, but not the correct term, at least professional translators use "Anschläge" to avoid ambiguity (how to evaluate the work with publishers): "Anschläge" are clearly not only visible letters, numbers, and punctuation, but also spaces and paragraphs (that makes quite a difference). Luckily, most programmes count them in a semiotic approach, so the correct term is IMHO "Anschläge" > "A".

**Comment by fletcher** [comment]
I made this change.

What about "Unsichtbare Zeichen anzeigen"?

**Comment by andreasvollmer** [comment]
This is OK.

**Comment by fletcher** [comment]
Thanks!
